package com.cactusteam.money.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ACCOUNT".
 */
public class Account implements ISyncObject {

    private Long id;
    /** Not-null value. */
    private String name;
    private boolean deleted;
    /** Not-null value. */
    private String currencyCode;
    /** Not-null value. */
    private String color;
    private int type;
    private boolean skipInBalance;
    private int customOrder;
    private Long globalId;
    private Boolean synced;

    // KEEP FIELDS - put your custom fields here
    public static final int CASH_TYPE = 0;
    public static final int SAVINGS_TYPE = 1;
    public static final int BANK_ACCOUNT_TYPE = 2;
    public static final int CARD_TYPE = 3;

    public static final int TYPE_NAME_SORT = 0;
    public static final int NAME_SORT = 1;
    public static final int CUSTOM_SORT = 2;

    private Double balance;
    private Double balanceInMain;
    // KEEP FIELDS END

    public Account() {
    }

    public Account(Long id) {
        this.id = id;
    }

    public Account(Long id, String name, boolean deleted, String currencyCode, String color, int type, boolean skipInBalance, int customOrder, Long globalId, Boolean synced) {
        this.id = id;
        this.name = name;
        this.deleted = deleted;
        this.currencyCode = currencyCode;
        this.color = color;
        this.type = type;
        this.skipInBalance = skipInBalance;
        this.customOrder = customOrder;
        this.globalId = globalId;
        this.synced = synced;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    /** Not-null value. */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /** Not-null value. */
    public String getColor() {
        return color;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setColor(String color) {
        this.color = color;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public boolean getSkipInBalance() {
        return skipInBalance;
    }

    public void setSkipInBalance(boolean skipInBalance) {
        this.skipInBalance = skipInBalance;
    }

    public int getCustomOrder() {
        return customOrder;
    }

    public void setCustomOrder(int customOrder) {
        this.customOrder = customOrder;
    }

    public Long getGlobalId() {
        return globalId;
    }

    public void setGlobalId(Long globalId) {
        this.globalId = globalId;
    }

    public Boolean getSynced() {
        return synced;
    }

    public void setSynced(Boolean synced) {
        this.synced = synced;
    }

    // KEEP METHODS - put your custom methods here

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public Double getBalanceInMain() {
        return balanceInMain;
    }

    public void setBalanceInMain(Double balanceInMain) {
        this.balanceInMain = balanceInMain;
    }

    public String getDisplayName() {
        return name + " - " + currencyCode;
    }
    // KEEP METHODS END

}
