package com.cactusteam.money.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BUDGET_PLAN_DEPENDENCY".
 */
public class BudgetPlanDependency {

    private Long id;
    private int refType;
    /** Not-null value. */
    private String refId;
    private long planId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BudgetPlanDependency() {
    }

    public BudgetPlanDependency(Long id) {
        this.id = id;
    }

    public BudgetPlanDependency(Long id, int refType, String refId, long planId) {
        this.id = id;
        this.refType = refType;
        this.refId = refId;
        this.planId = planId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRefType() {
        return refType;
    }

    public void setRefType(int refType) {
        this.refType = refType;
    }

    /** Not-null value. */
    public String getRefId() {
        return refId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRefId(String refId) {
        this.refId = refId;
    }

    public long getPlanId() {
        return planId;
    }

    public void setPlanId(long planId) {
        this.planId = planId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
