package com.cactusteam.money.data.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.cactusteam.money.data.dao.BudgetPlanDependency;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BUDGET_PLAN_DEPENDENCY".
*/
public class BudgetPlanDependencyDao extends AbstractDao<BudgetPlanDependency, Long> {

    public static final String TABLENAME = "BUDGET_PLAN_DEPENDENCY";

    /**
     * Properties of entity BudgetPlanDependency.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RefType = new Property(1, int.class, "refType", false, "REF_TYPE");
        public final static Property RefId = new Property(2, String.class, "refId", false, "REF_ID");
        public final static Property PlanId = new Property(3, long.class, "planId", false, "PLAN_ID");
    };

    private Query<BudgetPlanDependency> budgetPlan_DependenciesQuery;

    public BudgetPlanDependencyDao(DaoConfig config) {
        super(config);
    }
    
    public BudgetPlanDependencyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BUDGET_PLAN_DEPENDENCY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REF_TYPE\" INTEGER NOT NULL ," + // 1: refType
                "\"REF_ID\" TEXT NOT NULL ," + // 2: refId
                "\"PLAN_ID\" INTEGER NOT NULL );"); // 3: planId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BUDGET_PLAN_DEPENDENCY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BudgetPlanDependency entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRefType());
        stmt.bindString(3, entity.getRefId());
        stmt.bindLong(4, entity.getPlanId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BudgetPlanDependency readEntity(Cursor cursor, int offset) {
        BudgetPlanDependency entity = new BudgetPlanDependency( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // refType
            cursor.getString(offset + 2), // refId
            cursor.getLong(offset + 3) // planId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BudgetPlanDependency entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRefType(cursor.getInt(offset + 1));
        entity.setRefId(cursor.getString(offset + 2));
        entity.setPlanId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BudgetPlanDependency entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BudgetPlanDependency entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dependencies" to-many relationship of BudgetPlan. */
    public List<BudgetPlanDependency> _queryBudgetPlan_Dependencies(long planId) {
        synchronized (this) {
            if (budgetPlan_DependenciesQuery == null) {
                QueryBuilder<BudgetPlanDependency> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PlanId.eq(null));
                budgetPlan_DependenciesQuery = queryBuilder.build();
            }
        }
        Query<BudgetPlanDependency> query = budgetPlan_DependenciesQuery.forCurrentThread();
        query.setParameter(0, planId);
        return query.list();
    }

}
