package com.cactusteam.money.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SYNC_LOCK".
 */
public class SyncLock {

    private Long id;
    private int type;
    /** Not-null value. */
    private String lockId;
    private long time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SyncLock() {
    }

    public SyncLock(Long id) {
        this.id = id;
    }

    public SyncLock(Long id, int type, String lockId, long time) {
        this.id = id;
        this.type = type;
        this.lockId = lockId;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getLockId() {
        return lockId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLockId(String lockId) {
        this.lockId = lockId;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
