package com.cactusteam.money.data.dao;

import java.util.List;
import com.cactusteam.money.data.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "OPERATION".
 */
public class Transaction implements ISyncObject {

    private Long id;
    private int type;
    /** Not-null value. */
    private java.util.Date date;
    private String comment;
    private String ref;
    private Long globalId;
    private Boolean synced;
    private int status;
    private long sourceAccountId;
    private double amount;
    private Long categoryId;
    private Long subcategoryId;
    private Long destAccountId;
    private Double destAmount;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TransactionDao myDao;

    private Account sourceAccount;
    private Long sourceAccount__resolvedKey;

    private Category category;
    private Long category__resolvedKey;

    private Subcategory subcategory;
    private Long subcategory__resolvedKey;

    private Account destAccount;
    private Long destAccount__resolvedKey;

    private List<TransactionTag> tags;

    // KEEP FIELDS - put your custom fields here
    public static final int EXPENSE = 0;
    public static final int INCOME = 1;
    public static final int TRANSFER = 2;

    public static final int STATUS_COMPLETED = 0;
    public static final int STATUS_PLANNING = 1;
    public static final int STATUS_WAITING_CONFIRMATION = 2;


    private double amountInMainCurrency;
    private Double destAmountInMainCurrency;
    // KEEP FIELDS END

    public Transaction() {
    }

    public Transaction(Long id) {
        this.id = id;
    }

    public Transaction(Long id, int type, java.util.Date date, String comment, String ref, Long globalId, Boolean synced, int status, long sourceAccountId, double amount, Long categoryId, Long subcategoryId, Long destAccountId, Double destAmount) {
        this.id = id;
        this.type = type;
        this.date = date;
        this.comment = comment;
        this.ref = ref;
        this.globalId = globalId;
        this.synced = synced;
        this.status = status;
        this.sourceAccountId = sourceAccountId;
        this.amount = amount;
        this.categoryId = categoryId;
        this.subcategoryId = subcategoryId;
        this.destAccountId = destAccountId;
        this.destAmount = destAmount;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTransactionDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getRef() {
        return ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public Long getGlobalId() {
        return globalId;
    }

    public void setGlobalId(Long globalId) {
        this.globalId = globalId;
    }

    public Boolean getSynced() {
        return synced;
    }

    public void setSynced(Boolean synced) {
        this.synced = synced;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public long getSourceAccountId() {
        return sourceAccountId;
    }

    public void setSourceAccountId(long sourceAccountId) {
        this.sourceAccountId = sourceAccountId;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Long getSubcategoryId() {
        return subcategoryId;
    }

    public void setSubcategoryId(Long subcategoryId) {
        this.subcategoryId = subcategoryId;
    }

    public Long getDestAccountId() {
        return destAccountId;
    }

    public void setDestAccountId(Long destAccountId) {
        this.destAccountId = destAccountId;
    }

    public Double getDestAmount() {
        return destAmount;
    }

    public void setDestAmount(Double destAmount) {
        this.destAmount = destAmount;
    }

    /** To-one relationship, resolved on first access. */
    public Account getSourceAccount() {
        long __key = this.sourceAccountId;
        if (sourceAccount__resolvedKey == null || !sourceAccount__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AccountDao targetDao = daoSession.getAccountDao();
            Account sourceAccountNew = targetDao.load(__key);
            synchronized (this) {
                sourceAccount = sourceAccountNew;
            	sourceAccount__resolvedKey = __key;
            }
        }
        return sourceAccount;
    }

    public void setSourceAccount(Account sourceAccount) {
        if (sourceAccount == null) {
            throw new DaoException("To-one property 'sourceAccountId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.sourceAccount = sourceAccount;
            sourceAccountId = sourceAccount.getId();
            sourceAccount__resolvedKey = sourceAccountId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Category getCategory() {
        Long __key = this.categoryId;
        if (category__resolvedKey == null || !category__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CategoryDao targetDao = daoSession.getCategoryDao();
            Category categoryNew = targetDao.load(__key);
            synchronized (this) {
                category = categoryNew;
            	category__resolvedKey = __key;
            }
        }
        return category;
    }

    public void setCategory(Category category) {
        synchronized (this) {
            this.category = category;
            categoryId = category == null ? null : category.getId();
            category__resolvedKey = categoryId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Subcategory getSubcategory() {
        Long __key = this.subcategoryId;
        if (subcategory__resolvedKey == null || !subcategory__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SubcategoryDao targetDao = daoSession.getSubcategoryDao();
            Subcategory subcategoryNew = targetDao.load(__key);
            synchronized (this) {
                subcategory = subcategoryNew;
            	subcategory__resolvedKey = __key;
            }
        }
        return subcategory;
    }

    public void setSubcategory(Subcategory subcategory) {
        synchronized (this) {
            this.subcategory = subcategory;
            subcategoryId = subcategory == null ? null : subcategory.getId();
            subcategory__resolvedKey = subcategoryId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Account getDestAccount() {
        Long __key = this.destAccountId;
        if (destAccount__resolvedKey == null || !destAccount__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AccountDao targetDao = daoSession.getAccountDao();
            Account destAccountNew = targetDao.load(__key);
            synchronized (this) {
                destAccount = destAccountNew;
            	destAccount__resolvedKey = __key;
            }
        }
        return destAccount;
    }

    public void setDestAccount(Account destAccount) {
        synchronized (this) {
            this.destAccount = destAccount;
            destAccountId = destAccount == null ? null : destAccount.getId();
            destAccount__resolvedKey = destAccountId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<TransactionTag> getTags() {
        if (tags == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TransactionTagDao targetDao = daoSession.getTransactionTagDao();
            List<TransactionTag> tagsNew = targetDao._queryTransaction_Tags(id);
            synchronized (this) {
                if(tags == null) {
                    tags = tagsNew;
                }
            }
        }
        return tags;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetTags() {
        tags = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here

    public Transaction copy() {
        Transaction copy = new Transaction();
        copy.setType(type);
        copy.setDate(new java.util.Date());
        copy.setComment(comment);
        copy.setRef(ref);
        copy.status = status;
        copy.setSourceAccountId(sourceAccountId);
        copy.setAmount(amount);
        copy.setCategoryId(categoryId);
        copy.setSubcategoryId(subcategoryId);
        copy.setDestAccountId(destAccountId);
        copy.setDestAmount(destAmount);

        return copy;
    }

    public String getCategoryDisplayName() {
        Category category = getCategory();

        String categoryName = category != null ? category.getName() : "";
        Subcategory subcategory = getSubcategory();
        return subcategory == null ? categoryName : categoryName + " / " + subcategory.getName();
    }

    public double getAmountInMainCurrency() {
        return amountInMainCurrency;
    }

    public void setAmountInMainCurrency(double amountInMainCurrency) {
        this.amountInMainCurrency = amountInMainCurrency;
    }

    public void setDestAmountInMainCurrency(Double destAmountInMainCurrency) {
        this.destAmountInMainCurrency = destAmountInMainCurrency;
    }

    public Double getDestAmountInMainCurrency() {
        return destAmountInMainCurrency;
    }
    // KEEP METHODS END

}
