package com.cactusteam.money.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TRASH".
 */
public class Trash {

    private Long id;
    private int type;
    private long globalId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Trash() {
    }

    public Trash(Long id) {
        this.id = id;
    }

    public Trash(Long id, int type, long globalId) {
        this.id = id;
        this.type = type;
        this.globalId = globalId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public long getGlobalId() {
        return globalId;
    }

    public void setGlobalId(long globalId) {
        this.globalId = globalId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
